name: CI - Build & Push Image

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/ci-image.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-app" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        working-directory: app
        run: |
          docker build -t ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.SHA_TAG }} .
          docker tag  ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.SHA_TAG }} \
                      ${{ steps.vars.outputs.IMAGE }}:latest

      - name: Push image
        run: |
          docker push ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.SHA_TAG }}
          docker push ${{ steps.vars.outputs.IMAGE }}:latest
